"""empty message

Revision ID: 0074de103e1c
Revises: cc43cc1d9a32
Create Date: 2023-11-09 15:51:42.389764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0074de103e1c'
down_revision = 'cc43cc1d9a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lga', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('town')
        batch_op.drop_column('lga')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answer')
        batch_op.drop_column('question')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
